name: Run clang-format Linter

on:
  pull_request:
    types: closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: 'include examples test tools'
        extensions: 'hpp,cpp,ipp,h,c'
        clangFormatVersion: 14
        inplace: True
        style: file
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: YGM clang-format bot
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
